from .alexnet import *
from .resnet import *
from .resnet_zi import *
from .resnext import *
from .inception_resnet_v2 import *
from .googlenet import *
from .inception_v2 import *
from .mobilenet import *
from .mobilenet_v2 import *
from .densenet import *
from .mnist import *
from .evolved import *
from .efficientnet import *